/**
 * Bookable Services Configuration
 *
 * Maps the unified catalog to bookable service definitions
 * with prep times, cleanup times, room requirements, and booking rules.
 */

import type { BookableService, RoomId } from './types';

// ── BOOKABLE SERVICES CATALOG ──

export const BOOKABLE_SERVICES: BookableService[] = [
  // ═══ INJECTABLES (Room: Glow) ═══
  {
    id: 'botox',
    name: 'Botox',
    category: 'injectables',
    duration: 30,
    prepTime: 5,
    cleanupTime: 10,
    bufferTime: 15,
    price: 400,
    requiredRooms: ['glow'],
    requiredEquipment: ['Injectable Station'],
    requiresConsultation: true,
    isActive: true,
    rebookingIntervalDays: 90,
    preInstructions: [
      'Avoid alcohol for 24 hours before your appointment',
      'Discontinue blood thinners 7 days prior if medically safe',
      'Arrive with a clean face',
    ],
    postInstructions: [
      'Do not lie down for 4 hours after treatment',
      'Avoid strenuous exercise for 24 hours',
      'Do not massage or rub the treated area',
    ],
    canCombineWith: ['hydrafacial-signature', 'vi-peel'],
    depositRequired: 50,
    cancellationPolicy: 'strict',
  },
  {
    id: 'dysport',
    name: 'Dysport',
    category: 'injectables',
    duration: 30,
    prepTime: 5,
    cleanupTime: 10,
    bufferTime: 15,
    price: 400,
    requiredRooms: ['glow'],
    requiredEquipment: ['Injectable Station'],
    requiresConsultation: true,
    isActive: true,
    rebookingIntervalDays: 90,
    preInstructions: ['Avoid alcohol for 24 hours', 'Discontinue blood thinners 7 days prior if medically safe'],
    postInstructions: ['Do not lie down for 4 hours', 'Avoid exercise for 24 hours'],
    canCombineWith: ['hydrafacial-signature'],
    depositRequired: 50,
    cancellationPolicy: 'strict',
  },
  {
    id: 'filler-lips',
    name: 'Lip Filler',
    category: 'injectables',
    duration: 45,
    prepTime: 5,
    cleanupTime: 10,
    bufferTime: 15,
    price: 650,
    requiredRooms: ['glow'],
    requiredEquipment: ['Injectable Station'],
    requiresConsultation: true,
    isActive: true,
    rebookingIntervalDays: 365,
    preInstructions: ['Avoid alcohol 48 hours before', 'No dental work 2 weeks before/after'],
    postInstructions: ['Apply ice as needed', 'Avoid heat and exercise for 24 hours'],
    canCombineWith: [],
    depositRequired: 100,
    cancellationPolicy: 'strict',
  },
  {
    id: 'filler-cheeks',
    name: 'Cheek Filler',
    category: 'injectables',
    duration: 45,
    prepTime: 5,
    cleanupTime: 10,
    bufferTime: 15,
    price: 750,
    requiredRooms: ['glow'],
    requiredEquipment: ['Injectable Station'],
    requiresConsultation: true,
    isActive: true,
    rebookingIntervalDays: 365,
    preInstructions: ['Avoid alcohol 48 hours before'],
    postInstructions: ['Avoid pressure on treated area for 48 hours'],
    canCombineWith: [],
    depositRequired: 100,
    cancellationPolicy: 'strict',
  },
  {
    id: 'filler-jawline',
    name: 'Jawline Filler',
    category: 'injectables',
    duration: 60,
    prepTime: 5,
    cleanupTime: 10,
    bufferTime: 15,
    price: 900,
    requiredRooms: ['glow'],
    requiredEquipment: ['Injectable Station'],
    requiresConsultation: true,
    isActive: true,
    rebookingIntervalDays: 365,
    preInstructions: ['Avoid alcohol 48 hours before'],
    postInstructions: ['Sleep elevated for 2 nights'],
    canCombineWith: [],
    depositRequired: 100,
    cancellationPolicy: 'strict',
  },
  {
    id: 'filler-undereyes',
    name: 'Under-Eye Filler',
    category: 'injectables',
    duration: 45,
    prepTime: 5,
    cleanupTime: 10,
    bufferTime: 15,
    price: 800,
    requiredRooms: ['glow'],
    requiredEquipment: ['Injectable Station'],
    requiresConsultation: true,
    isActive: true,
    rebookingIntervalDays: 365,
    preInstructions: ['Discontinue blood thinners 7-10 days prior', 'Get good sleep'],
    postInstructions: ['Apply ice gently', 'No rubbing for 48 hours'],
    canCombineWith: [],
    depositRequired: 100,
    cancellationPolicy: 'strict',
  },

  // ═══ HYDRAFACIAL (Room: Aura) ═══
  {
    id: 'hydrafacial-express',
    name: 'Express Facial',
    category: 'facial',
    duration: 60,
    prepTime: 5,
    cleanupTime: 10,
    bufferTime: 15,
    price: 99,
    requiredRooms: ['aura'],
    requiredEquipment: ['HydraFacial'],
    requiresConsultation: false,
    isActive: true,
    rebookingIntervalDays: 21,
    preInstructions: ['No special preparation needed'],
    postInstructions: ['Avoid direct sun for 24 hours', 'Apply SPF'],
    canCombineWith: ['hydrafacial-dermaplaning', 'hydrafacial-red-light'],
    depositRequired: 0,
    cancellationPolicy: 'standard',
  },
  {
    id: 'hydrafacial-signature',
    name: 'Signature HydraFacial',
    category: 'facial',
    duration: 60,
    prepTime: 5,
    cleanupTime: 10,
    bufferTime: 15,
    price: 225,
    requiredRooms: ['aura'],
    requiredEquipment: ['HydraFacial'],
    requiresConsultation: false,
    isActive: true,
    rebookingIntervalDays: 30,
    preInstructions: ['Come as you are', 'Avoid retinoids 2-3 days before for sensitive skin'],
    postInstructions: ['Apply SPF', 'Avoid harsh products for 24 hours'],
    canCombineWith: ['botox', 'dysport', 'hydrafacial-dermaplaning', 'hydrafacial-red-light', 'hydrafacial-neck-decollete'],
    depositRequired: 0,
    cancellationPolicy: 'standard',
  },
  {
    id: 'hydrafacial-back',
    name: 'Back HydraFacial',
    category: 'facial',
    duration: 45,
    prepTime: 5,
    cleanupTime: 10,
    bufferTime: 15,
    price: 325,
    requiredRooms: ['aura'],
    requiredEquipment: ['HydraFacial'],
    requiresConsultation: false,
    isActive: true,
    rebookingIntervalDays: 30,
    preInstructions: ['Wear a top that is easy to remove'],
    postInstructions: ['Avoid tight clothing on back for 24 hours'],
    canCombineWith: [],
    depositRequired: 0,
    cancellationPolicy: 'standard',
  },
  {
    id: 'hydrafacial-keravive',
    name: 'Keravive Scalp Treatment',
    category: 'facial',
    duration: 60,
    prepTime: 5,
    cleanupTime: 10,
    bufferTime: 15,
    price: 575,
    requiredRooms: ['aura'],
    requiredEquipment: ['HydraFacial'],
    requiresConsultation: false,
    isActive: true,
    rebookingIntervalDays: 30,
    preInstructions: ['Arrive with clean, dry hair'],
    postInstructions: ['Do not wash hair for 24 hours'],
    canCombineWith: [],
    depositRequired: 50,
    cancellationPolicy: 'standard',
  },

  // ═══ CHEMICAL PEELS (Room: Aura) ═══
  {
    id: 'vi-peel',
    name: 'VI Peel',
    category: 'chemical-peel',
    duration: 30,
    prepTime: 5,
    cleanupTime: 10,
    bufferTime: 15,
    price: 325,
    requiredRooms: ['aura'],
    requiredEquipment: ['VI Peel'],
    requiresConsultation: false,
    isActive: true,
    rebookingIntervalDays: 28,
    preInstructions: ['Discontinue retinoids 5-7 days before', 'No waxing 7 days before'],
    postInstructions: ['Follow the VI Peel post-care kit instructions carefully'],
    canCombineWith: ['hydrafacial-signature'],
    depositRequired: 0,
    cancellationPolicy: 'standard',
  },
  {
    id: 'biorepeel-face',
    name: 'BioRePeel Face',
    category: 'chemical-peel',
    duration: 60,
    prepTime: 5,
    cleanupTime: 10,
    bufferTime: 15,
    price: 350,
    requiredRooms: ['aura'],
    requiredEquipment: ['BioRePeel'],
    requiresConsultation: false,
    isActive: true,
    rebookingIntervalDays: 28,
    preInstructions: ['Discontinue retinoids 3-5 days before'],
    postInstructions: ['Apply SPF daily', 'Avoid active products for 48 hours'],
    canCombineWith: ['hydrafacial-signature'],
    depositRequired: 0,
    cancellationPolicy: 'standard',
  },
  {
    id: 'prx-t33-face',
    name: 'PRX-T33 Face',
    category: 'chemical-peel',
    duration: 60,
    prepTime: 5,
    cleanupTime: 10,
    bufferTime: 15,
    price: 495,
    requiredRooms: ['aura'],
    requiredEquipment: ['PRX-T33'],
    requiresConsultation: false,
    isActive: true,
    rebookingIntervalDays: 28,
    preInstructions: ['Discontinue retinoids 5 days before'],
    postInstructions: ['Keep skin moisturized', 'Apply SPF daily'],
    canCombineWith: [],
    depositRequired: 0,
    cancellationPolicy: 'standard',
  },
  {
    id: 'cosmelan-peel',
    name: 'Cosmelan Peel',
    category: 'chemical-peel',
    duration: 90,
    prepTime: 10,
    cleanupTime: 15,
    bufferTime: 25,
    price: 1399,
    requiredRooms: ['aura'],
    requiredEquipment: ['Cosmelan'],
    requiresConsultation: true,
    isActive: true,
    rebookingIntervalDays: 90,
    preInstructions: [
      'Discontinue retinoids and AHAs 7 days before',
      'Avoid sun exposure 2 weeks before',
      'Arrive with clean skin — no makeup or products',
    ],
    postInstructions: [
      'Apply Cosmelan 2 cream at home as directed — this is critical for results',
      'Strict SPF 50+ daily — no exceptions',
      'Avoid sun exposure for 4 weeks',
      'Expect peeling days 3-7',
    ],
    canCombineWith: [],
    depositRequired: 200,
    cancellationPolicy: 'strict',
  },
  {
    id: 'microneedling-arrissence-undereye',
    name: 'Microneedling with Arrissence — Dark Undereyes',
    category: 'rf-microneedling',
    duration: 60,
    prepTime: 10,
    cleanupTime: 15,
    bufferTime: 25,
    price: 695,
    requiredRooms: ['halo'],
    requiredEquipment: ['Cutera Secret RF', 'Arrissence Serum'],
    requiresConsultation: false,
    isActive: true,
    rebookingIntervalDays: 42,
    preInstructions: [
      'No makeup or eye products on day of appointment',
      'Discontinue retinoids 5 days before',
      'Avoid blood thinners 3-5 days before if medically safe',
    ],
    postInstructions: [
      'No makeup for 24 hours',
      'Avoid rubbing eye area for 48 hours',
      'Apply recommended eye serum as directed',
      'Mild bruising or swelling normal for 2-3 days',
    ],
    canCombineWith: [],
    depositRequired: 0,
    cancellationPolicy: 'standard',
  },

  // ═══ LASER FACIAL (Room: Aura) ═══
  {
    id: 'laser-facial-ndyag',
    name: 'ND:Yag Laser Facial',
    category: 'laser',
    duration: 90,
    prepTime: 10,
    cleanupTime: 15,
    bufferTime: 25,
    price: 475,
    requiredRooms: ['aura'],
    requiredEquipment: ['ND:YAG Laser'],
    requiresConsultation: true,
    isActive: true,
    rebookingIntervalDays: 42,
    preInstructions: ['No sun exposure 2 weeks before', 'Discontinue retinoids 5-7 days before'],
    postInstructions: ['Apply SPF 30+ daily', 'Avoid heat for 48 hours'],
    canCombineWith: [],
    depositRequired: 50,
    cancellationPolicy: 'strict',
  },

  // ═══ RF MICRONEEDLING (Room: Halo) ═══
  {
    id: 'rf-microneedling-face',
    name: 'RF Microneedling - Full Face',
    category: 'rf-microneedling',
    duration: 90,
    prepTime: 10,
    cleanupTime: 15,
    bufferTime: 25,
    price: 750,
    requiredRooms: ['halo'],
    requiredEquipment: ['Cutera Secret RF'],
    requiresConsultation: true,
    isActive: true,
    rebookingIntervalDays: 42,
    preInstructions: ['No sun 2 weeks before', 'Discontinue retinoids 7 days before'],
    postInstructions: ['Apply provided serum', 'No makeup for 24 hours'],
    canCombineWith: [],
    depositRequired: 100,
    cancellationPolicy: 'strict',
  },
  {
    id: 'rf-microneedling-face-neck',
    name: 'RF Microneedling - Face & Neck',
    category: 'rf-microneedling',
    duration: 90,
    prepTime: 10,
    cleanupTime: 15,
    bufferTime: 25,
    price: 1100,
    requiredRooms: ['halo'],
    requiredEquipment: ['Cutera Secret RF'],
    requiresConsultation: true,
    isActive: true,
    rebookingIntervalDays: 42,
    preInstructions: ['No sun 2 weeks before', 'Discontinue retinoids 7 days before'],
    postInstructions: ['Apply provided serum', 'No makeup for 24 hours'],
    canCombineWith: [],
    depositRequired: 100,
    cancellationPolicy: 'strict',
  },

  // ═══ SOFWAVE (Room: Halo) ═══
  {
    id: 'sofwave-full-face',
    name: 'Sofwave - Full Face',
    category: 'skin-tightening',
    duration: 60,
    prepTime: 10,
    cleanupTime: 10,
    bufferTime: 20,
    price: 2250,
    requiredRooms: ['halo'],
    requiredEquipment: ['Sofwave'],
    requiresConsultation: true,
    isActive: true,
    rebookingIntervalDays: 365,
    preInstructions: ['No special prep — arrive with clean skin'],
    postInstructions: ['Mild redness is normal', 'Resume normal activities immediately'],
    canCombineWith: [],
    depositRequired: 250,
    cancellationPolicy: 'strict',
  },
  {
    id: 'sofwave-full-face-neck',
    name: 'Sofwave - Full Face + Neck',
    category: 'skin-tightening',
    duration: 90,
    prepTime: 10,
    cleanupTime: 10,
    bufferTime: 20,
    price: 3999,
    requiredRooms: ['halo'],
    requiredEquipment: ['Sofwave'],
    requiresConsultation: true,
    isActive: true,
    rebookingIntervalDays: 365,
    preInstructions: ['No special prep — arrive with clean skin'],
    postInstructions: ['Mild redness is normal', 'Resume normal activities immediately'],
    canCombineWith: [],
    depositRequired: 400,
    cancellationPolicy: 'strict',
  },

  // ═══ LASER HAIR REMOVAL (Room: Glow) ═══
  ...generateLHRServices(),

  // ═══ WELLNESS INJECTIONS (Room: Glow) ═══
  {
    id: 'wellness-vitamin-d3',
    name: 'Vitamin D3 Injection',
    category: 'wellness',
    duration: 15,
    prepTime: 5,
    cleanupTime: 5,
    bufferTime: 10,
    price: 50,
    requiredRooms: ['glow'],
    requiredEquipment: [],
    requiresConsultation: false,
    isActive: true,
    rebookingIntervalDays: 7,
    preInstructions: ['Stay hydrated', 'Eat a light meal'],
    postInstructions: ['Drink water', 'Minor soreness at injection site is normal'],
    canCombineWith: ['wellness-b12', 'wellness-tri-immune', 'wellness-glutathione'],
    depositRequired: 0,
    cancellationPolicy: 'standard',
  },
  {
    id: 'wellness-b12',
    name: 'B12 Injection',
    category: 'wellness',
    duration: 15,
    prepTime: 5,
    cleanupTime: 5,
    bufferTime: 10,
    price: 35,
    requiredRooms: ['glow'],
    requiredEquipment: [],
    requiresConsultation: false,
    isActive: true,
    rebookingIntervalDays: 7,
    preInstructions: ['Stay hydrated'],
    postInstructions: ['Drink water'],
    canCombineWith: ['wellness-vitamin-d3', 'wellness-tri-immune', 'wellness-glutathione'],
    depositRequired: 0,
    cancellationPolicy: 'standard',
  },
  {
    id: 'wellness-tri-immune',
    name: 'Tri-Immune Injection',
    category: 'wellness',
    duration: 15,
    prepTime: 5,
    cleanupTime: 5,
    bufferTime: 10,
    price: 75,
    requiredRooms: ['glow'],
    requiredEquipment: [],
    requiresConsultation: false,
    isActive: true,
    rebookingIntervalDays: 7,
    preInstructions: ['Stay hydrated', 'Eat a light meal'],
    postInstructions: ['Drink water'],
    canCombineWith: ['wellness-vitamin-d3', 'wellness-b12', 'wellness-glutathione'],
    depositRequired: 0,
    cancellationPolicy: 'standard',
  },
  {
    id: 'wellness-glutathione',
    name: 'Glutathione Injection',
    category: 'wellness',
    duration: 15,
    prepTime: 5,
    cleanupTime: 5,
    bufferTime: 10,
    price: 100,
    requiredRooms: ['glow'],
    requiredEquipment: [],
    requiresConsultation: false,
    isActive: true,
    rebookingIntervalDays: 7,
    preInstructions: ['Stay hydrated'],
    postInstructions: ['Drink water', 'You may notice a garlic-like taste — this is normal'],
    canCombineWith: ['wellness-vitamin-d3', 'wellness-b12', 'wellness-tri-immune'],
    depositRequired: 0,
    cancellationPolicy: 'standard',
  },
  {
    id: 'wellness-nad-plus',
    name: 'NAD+ Injection',
    category: 'wellness',
    duration: 30,
    prepTime: 5,
    cleanupTime: 5,
    bufferTime: 10,
    price: 150,
    requiredRooms: ['glow'],
    requiredEquipment: [],
    requiresConsultation: false,
    isActive: true,
    rebookingIntervalDays: 14,
    preInstructions: ['Stay hydrated', 'Eat before your appointment'],
    postInstructions: ['Drink plenty of water', 'Rest if you feel flushed — this is normal'],
    canCombineWith: [],
    depositRequired: 0,
    cancellationPolicy: 'standard',
  },

  // ═══ CONSULTATIONS (Room: Glow or any) ═══
  {
    id: 'consult-aesthetic',
    name: 'Aesthetic Consultation',
    category: 'consultation',
    duration: 30,
    prepTime: 5,
    cleanupTime: 5,
    bufferTime: 10,
    price: 0,
    requiredRooms: [],
    requiredEquipment: [],
    requiresConsultation: false,
    isActive: true,
    rebookingIntervalDays: 0,
    preInstructions: ['Come with a clean face if possible', 'Bring photos of your goals if you have them'],
    postInstructions: [],
    canCombineWith: [],
    depositRequired: 0,
    cancellationPolicy: 'standard',
  },
  {
    id: 'consult-wellness',
    name: 'Wellness Consultation',
    category: 'consultation',
    duration: 30,
    prepTime: 5,
    cleanupTime: 5,
    bufferTime: 10,
    price: 0,
    requiredRooms: [],
    requiredEquipment: [],
    requiresConsultation: false,
    isActive: true,
    rebookingIntervalDays: 0,
    preInstructions: ['Bring a list of current medications and supplements'],
    postInstructions: [],
    canCombineWith: [],
    depositRequired: 0,
    cancellationPolicy: 'standard',
  },
  {
    id: 'consult-injectable',
    name: 'Injectable Consultation',
    category: 'consultation',
    duration: 30,
    prepTime: 5,
    cleanupTime: 5,
    bufferTime: 10,
    price: 0,
    requiredRooms: ['glow'],
    requiredEquipment: [],
    requiresConsultation: false,
    isActive: true,
    rebookingIntervalDays: 0,
    preInstructions: ['Come with a clean face', 'Bring photos of your desired look'],
    postInstructions: [],
    canCombineWith: [],
    depositRequired: 0,
    cancellationPolicy: 'standard',
  },
];

// ── LHR SERVICE GENERATOR ──

function generateLHRServices(): BookableService[] {
  const lhrAreas: { id: string; name: string; duration: number; price: number }[] = [
    { id: 'lhr-upper-lip', name: 'LHR - Upper Lip', duration: 5, price: 79 },
    { id: 'lhr-chin', name: 'LHR - Chin', duration: 8, price: 79 },
    { id: 'lhr-full-face', name: 'LHR - Full Face', duration: 25, price: 275 },
    { id: 'lhr-underarms', name: 'LHR - Underarms', duration: 10, price: 149 },
    { id: 'lhr-full-arms', name: 'LHR - Full Arms', duration: 28, price: 375 },
    { id: 'lhr-full-brazilian', name: 'LHR - Full Brazilian', duration: 20, price: 225 },
    { id: 'lhr-half-legs', name: 'LHR - Half Legs', duration: 23, price: 225 },
    { id: 'lhr-full-legs', name: 'LHR - Full Legs', duration: 43, price: 375 },
    { id: 'lhr-full-back', name: 'LHR - Full Back', duration: 35, price: 375 },
    { id: 'lhr-full-body', name: 'LHR - Full Body', duration: 105, price: 1199 },
  ];

  return lhrAreas.map(area => ({
    id: area.id,
    name: area.name,
    category: 'laser-hair-removal',
    duration: area.duration,
    prepTime: 5,
    cleanupTime: 5,
    bufferTime: 10,
    price: area.price,
    requiredRooms: ['glow'] as RoomId[],
    requiredEquipment: ['Laser Hair Removal'],
    requiresConsultation: false,
    isActive: true,
    rebookingIntervalDays: 42, // 6 weeks between sessions
    preInstructions: [
      'Shave the treatment area 24 hours before',
      'No waxing/plucking/threading for 4 weeks before',
      'No sun exposure or self-tanner for 2 weeks before',
      'Arrive with clean skin — no lotions or products',
    ],
    postInstructions: [
      'Apply aloe vera or soothing cream',
      'Avoid sun exposure for 2 weeks',
      'No hot baths/saunas for 48 hours',
    ],
    canCombineWith: [] as string[],
    depositRequired: area.price >= 300 ? 50 : 0,
    cancellationPolicy: 'standard' as const,
  }));
}

// ── HELPERS ──

export function getServiceById(serviceId: string): BookableService | undefined {
  return BOOKABLE_SERVICES.find(s => s.id === serviceId);
}

export function getServicesByCategory(category: string): BookableService[] {
  return BOOKABLE_SERVICES.filter(s => s.category === category && s.isActive);
}

export function getBookableCategories(): { id: string; name: string; count: number }[] {
  const categories = new Map<string, number>();
  for (const svc of BOOKABLE_SERVICES.filter(s => s.isActive)) {
    categories.set(svc.category, (categories.get(svc.category) ?? 0) + 1);
  }

  const categoryNames: Record<string, string> = {
    'injectables': 'Injectables',
    'facial': 'HydraFacial',
    'chemical-peel': 'Chemical Peels',
    'laser': 'Laser Treatments',
    'rf-microneedling': 'RF Microneedling',
    'skin-tightening': 'Skin Tightening',
    'laser-hair-removal': 'Laser Hair Removal',
    'wellness': 'Wellness Injections',
    'consultation': 'Consultations',
  };

  return Array.from(categories.entries()).map(([id, count]) => ({
    id,
    name: categoryNames[id] ?? id,
    count,
  }));
}
