import { NextRequest, NextResponse } from 'next/server';
import { filterNotes, buildClientTimeline, createNote } from '@/lib/crm/notes';
import type { CRMNote, NoteFilter } from '@/types/crm';

/**
 * GET /api/dashboard/crm/notes
 * Returns notes, optionally filtered by clientId.
 */
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const clientId = searchParams.get('clientId') || undefined;
    const type = searchParams.get('type') || undefined;
    const search = searchParams.get('q') || undefined;

    let notes = getSampleNotes();

    const filter: NoteFilter = {};
    if (clientId) filter.clientId = clientId;
    if (type) filter.type = type as NoteFilter['type'];
    if (search) filter.searchQuery = search;

    notes = filterNotes(notes, filter);

    return NextResponse.json(notes);
  } catch (error) {
    console.error('CRM Notes error:', error);
    return NextResponse.json({ error: 'Failed to load notes' }, { status: 500 });
  }
}

/**
 * POST /api/dashboard/crm/notes
 * Create a new note.
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const note = createNote({
      clientId: body.clientId,
      clientName: body.clientName,
      type: body.type,
      subject: body.subject,
      content: body.content,
      createdBy: body.createdBy || 'Rina',
      isPinned: body.isPinned,
      mentions: body.mentions,
      tags: body.tags,
    });

    return NextResponse.json({ success: true, note });
  } catch (error) {
    console.error('CRM Notes POST error:', error);
    return NextResponse.json({ error: 'Failed to create note' }, { status: 500 });
  }
}

function getSampleNotes(): CRMNote[] {
  return [
    {
      id: 'note_001', clientId: 'c001', clientName: 'Sarah Johnson', type: 'call',
      subject: 'Initial consultation call', content: 'Discussed injection treatment options. Client interested in Botox for forehead lines and crow\'s feet. Mentioned friend referral.',
      createdBy: 'Rina', createdAt: '2026-03-25T14:30:00Z', updatedAt: '2026-03-25T14:30:00Z',
      isPinned: false, mentions: [], tags: ['injectable', 'new_lead'], attachments: [], isAutoGenerated: false,
    },
    {
      id: 'note_002', clientId: 'c003', clientName: 'Michelle Park', type: 'in_person',
      subject: 'Sofwave consultation completed', content: 'Full face and neck Sofwave consultation. Client very interested in Platinum package. Discussed financing options.',
      createdBy: 'Rina', createdAt: '2026-03-20T11:00:00Z', updatedAt: '2026-03-20T11:00:00Z',
      isPinned: true, mentions: ['Rina'], tags: ['sofwave', 'vip', 'consultation'], attachments: [], isAutoGenerated: false,
    },
    {
      id: 'note_003', clientId: 'c002', clientName: 'Emily Chen', type: 'email',
      subject: 'Pre-consultation prep sent', content: 'Sent pre-consultation preparation instructions for upcoming Sofwave consultation.',
      createdBy: 'system', createdAt: '2026-03-22T09:00:00Z', updatedAt: '2026-03-22T09:00:00Z',
      isPinned: false, mentions: [], tags: ['auto_generated', 'pre_consult'], attachments: [], automationId: 'auto_005', isAutoGenerated: true,
    },
  ];
}
