/**
 * Activity Logging & Notes Engine for Rani Beauty Clinic CRM
 *
 * Note types: call, email, text, in-person, internal.
 * Supports client timeline, auto-generated notes, templates, mentions, pinning.
 */

import type {
  CRMNote,
  NoteType,
  NoteTemplate,
  NoteAttachment,
  ClientTimeline,
  TimelineEvent,
  TimelineEventType,
} from '@/types/crm';

// ─────────────────────────────────────────────────────────────
// NOTE CREATION
// ─────────────────────────────────────────────────────────────

/**
 * Create a new CRM note.
 */
export function createNote(input: {
  clientId: string;
  clientName: string;
  type: NoteType;
  subject: string;
  content: string;
  createdBy: string;
  isPinned?: boolean;
  mentions?: string[];
  tags?: string[];
  attachments?: NoteAttachment[];
  automationId?: string;
  isAutoGenerated?: boolean;
}): CRMNote {
  const now = new Date().toISOString();
  return {
    id: `note_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`,
    clientId: input.clientId,
    clientName: input.clientName,
    type: input.type,
    subject: input.subject,
    content: input.content,
    createdBy: input.createdBy,
    createdAt: now,
    updatedAt: now,
    isPinned: input.isPinned || false,
    mentions: input.mentions || [],
    tags: input.tags || [],
    attachments: input.attachments || [],
    automationId: input.automationId,
    isAutoGenerated: input.isAutoGenerated || false,
  };
}

/**
 * Create an auto-generated note from a system event.
 */
export function createAutoNote(
  clientId: string,
  clientName: string,
  event: string,
  details: string,
  automationId?: string,
): CRMNote {
  return createNote({
    clientId,
    clientName,
    type: 'internal',
    subject: event,
    content: details,
    createdBy: 'system',
    isAutoGenerated: true,
    automationId,
    tags: ['auto_generated'],
  });
}

// ─────────────────────────────────────────────────────────────
// NOTE MANAGEMENT
// ─────────────────────────────────────────────────────────────

/**
 * Pin or unpin a note.
 */
export function togglePin(note: CRMNote): CRMNote {
  return {
    ...note,
    isPinned: !note.isPinned,
    updatedAt: new Date().toISOString(),
  };
}

/**
 * Update a note's content.
 */
export function updateNote(
  note: CRMNote,
  updates: { subject?: string; content?: string; tags?: string[]; mentions?: string[] },
): CRMNote {
  return {
    ...note,
    ...updates,
    updatedAt: new Date().toISOString(),
  };
}

/**
 * Add a mention to a note.
 */
export function addMention(note: CRMNote, mention: string): CRMNote {
  if (note.mentions.includes(mention)) return note;
  return {
    ...note,
    mentions: [...note.mentions, mention],
    updatedAt: new Date().toISOString(),
  };
}

// ─────────────────────────────────────────────────────────────
// NOTE TEMPLATES
// ─────────────────────────────────────────────────────────────

export const NOTE_TEMPLATES: NoteTemplate[] = [
  {
    id: 'tpl_call_followup',
    name: 'Follow-Up Call',
    type: 'call',
    subject: 'Follow-up call with {{clientName}}',
    content: 'Called {{clientName}} regarding {{reason}}.\n\nOutcome: {{outcome}}\nNext steps: {{nextSteps}}\nFollow-up date: {{followUpDate}}',
    variables: ['clientName', 'reason', 'outcome', 'nextSteps', 'followUpDate'],
  },
  {
    id: 'tpl_consult_notes',
    name: 'Consultation Notes',
    type: 'in_person',
    subject: 'Consultation with {{clientName}}',
    content: 'Consultation completed with {{clientName}}.\n\nConcerns discussed: {{concerns}}\nRecommended treatments: {{treatments}}\nTreatment plan tier: {{planTier}}\nEstimated investment: {{estimatedValue}}\nClient sentiment: {{sentiment}}\nNext steps: {{nextSteps}}',
    variables: ['clientName', 'concerns', 'treatments', 'planTier', 'estimatedValue', 'sentiment', 'nextSteps'],
  },
  {
    id: 'tpl_post_treatment',
    name: 'Post-Treatment Check-In',
    type: 'call',
    subject: 'Post-treatment check-in: {{clientName}}',
    content: 'Post-treatment follow-up call for {{clientName}} ({{serviceName}}).\n\nHow are they feeling: {{feeling}}\nAny concerns: {{concerns}}\nSatisfaction level: {{satisfaction}}\nRebook discussed: {{rebookDiscussed}}',
    variables: ['clientName', 'serviceName', 'feeling', 'concerns', 'satisfaction', 'rebookDiscussed'],
  },
  {
    id: 'tpl_email_sent',
    name: 'Email Sent',
    type: 'email',
    subject: 'Email sent to {{clientName}}: {{emailSubject}}',
    content: 'Sent email to {{clientName}} ({{email}}).\n\nSubject: {{emailSubject}}\nType: {{emailType}}\nTemplate: {{template}}',
    variables: ['clientName', 'email', 'emailSubject', 'emailType', 'template'],
  },
  {
    id: 'tpl_sms_sent',
    name: 'Text Message Sent',
    type: 'text',
    subject: 'SMS sent to {{clientName}}',
    content: 'Text message sent to {{clientName}} ({{phone}}).\n\nMessage: {{message}}\nType: {{messageType}}',
    variables: ['clientName', 'phone', 'message', 'messageType'],
  },
  {
    id: 'tpl_internal',
    name: 'Internal Note',
    type: 'internal',
    subject: '{{subject}}',
    content: '{{content}}',
    variables: ['subject', 'content'],
  },
  {
    id: 'tpl_objection',
    name: 'Objection Handling',
    type: 'call',
    subject: 'Objection: {{clientName}} - {{objectionType}}',
    content: 'Client {{clientName}} raised objection during {{context}}.\n\nObjection type: {{objectionType}}\nDetails: {{details}}\nResponse used: {{response}}\nOutcome: {{outcome}}\nFollow-up needed: {{followUpNeeded}}',
    variables: ['clientName', 'context', 'objectionType', 'details', 'response', 'outcome', 'followUpNeeded'],
  },
  {
    id: 'tpl_referral',
    name: 'Referral Received',
    type: 'internal',
    subject: 'Referral from {{referrerName}}',
    content: 'New referral received.\n\nReferred by: {{referrerName}}\nNew prospect: {{clientName}}\nInterested in: {{interests}}\nReferral source: {{source}}\nCredit applied: {{creditApplied}}',
    variables: ['referrerName', 'clientName', 'interests', 'source', 'creditApplied'],
  },
];

/**
 * Get a note template by ID.
 */
export function getTemplate(templateId: string): NoteTemplate | undefined {
  return NOTE_TEMPLATES.find(t => t.id === templateId);
}

/**
 * Render a template with variable substitution.
 */
export function renderTemplate(
  template: NoteTemplate,
  variables: Record<string, string>,
): { subject: string; content: string } {
  let subject = template.subject;
  let content = template.content;

  for (const [key, value] of Object.entries(variables)) {
    const placeholder = `{{${key}}}`;
    subject = subject.replace(new RegExp(placeholder.replace(/[{}]/g, '\\$&'), 'g'), value);
    content = content.replace(new RegExp(placeholder.replace(/[{}]/g, '\\$&'), 'g'), value);
  }

  return { subject, content };
}

// ─────────────────────────────────────────────────────────────
// CLIENT TIMELINE
// ─────────────────────────────────────────────────────────────

const EVENT_ICONS: Record<TimelineEventType, string> = {
  note: 'FileText',
  stage_change: 'ArrowRight',
  appointment: 'Calendar',
  transaction: 'DollarSign',
  membership: 'Crown',
  task: 'CheckSquare',
  automation: 'Zap',
  milestone: 'Award',
  review: 'Star',
};

const EVENT_COLORS: Record<TimelineEventType, string> = {
  note: 'bg-blue-100 text-blue-700',
  stage_change: 'bg-purple-100 text-purple-700',
  appointment: 'bg-green-100 text-green-700',
  transaction: 'bg-emerald-100 text-emerald-700',
  membership: 'bg-amber-100 text-amber-700',
  task: 'bg-orange-100 text-orange-700',
  automation: 'bg-cyan-100 text-cyan-700',
  milestone: 'bg-yellow-100 text-yellow-700',
  review: 'bg-pink-100 text-pink-700',
};

/**
 * Build a unified client timeline from various data sources.
 */
export function buildClientTimeline(
  clientId: string,
  clientName: string,
  data: {
    notes?: CRMNote[];
    appointments?: { id: string; service: string; date: string; provider: string; status: string }[];
    transactions?: { id: string; date: string; amount: number; service: string; type: string }[];
    stageChanges?: { from: string; to: string; at: string; by: string }[];
    milestones?: { label: string; achievedAt?: string }[];
    automations?: { name: string; triggeredAt: string; status: string }[];
    reviews?: { id: string; rating: number; date: string; platform: string }[];
  },
): ClientTimeline {
  const events: TimelineEvent[] = [];

  // Notes
  if (data.notes) {
    for (const note of data.notes) {
      events.push({
        id: note.id,
        type: 'note',
        title: note.subject,
        description: note.content.substring(0, 200),
        timestamp: note.createdAt,
        actor: note.createdBy,
        metadata: { noteType: note.type, isPinned: note.isPinned },
        icon: EVENT_ICONS.note,
        color: EVENT_COLORS.note,
      });
    }
  }

  // Appointments
  if (data.appointments) {
    for (const appt of data.appointments) {
      events.push({
        id: appt.id,
        type: 'appointment',
        title: `${appt.service} appointment`,
        description: `${appt.status} - with ${appt.provider}`,
        timestamp: appt.date,
        actor: appt.provider,
        metadata: { service: appt.service, status: appt.status },
        icon: EVENT_ICONS.appointment,
        color: EVENT_COLORS.appointment,
      });
    }
  }

  // Transactions
  if (data.transactions) {
    for (const tx of data.transactions) {
      events.push({
        id: tx.id,
        type: 'transaction',
        title: `$${tx.amount.toLocaleString()} - ${tx.service}`,
        description: `${tx.type} payment`,
        timestamp: tx.date,
        actor: 'system',
        metadata: { amount: tx.amount, service: tx.service },
        icon: EVENT_ICONS.transaction,
        color: EVENT_COLORS.transaction,
      });
    }
  }

  // Stage changes
  if (data.stageChanges) {
    for (const change of data.stageChanges) {
      events.push({
        id: `stage_${change.at}`,
        type: 'stage_change',
        title: `Stage: ${change.from} → ${change.to}`,
        description: `Moved by ${change.by}`,
        timestamp: change.at,
        actor: change.by,
        metadata: { from: change.from, to: change.to },
        icon: EVENT_ICONS.stage_change,
        color: EVENT_COLORS.stage_change,
      });
    }
  }

  // Milestones
  if (data.milestones) {
    for (const milestone of data.milestones) {
      if (milestone.achievedAt) {
        events.push({
          id: `milestone_${milestone.label}`,
          type: 'milestone',
          title: `Milestone: ${milestone.label}`,
          description: 'Achievement unlocked',
          timestamp: milestone.achievedAt,
          actor: 'system',
          icon: EVENT_ICONS.milestone,
          color: EVENT_COLORS.milestone,
        });
      }
    }
  }

  // Automations
  if (data.automations) {
    for (const auto of data.automations) {
      events.push({
        id: `auto_${auto.triggeredAt}`,
        type: 'automation',
        title: `Automation: ${auto.name}`,
        description: auto.status,
        timestamp: auto.triggeredAt,
        actor: 'system',
        icon: EVENT_ICONS.automation,
        color: EVENT_COLORS.automation,
      });
    }
  }

  // Reviews
  if (data.reviews) {
    for (const review of data.reviews) {
      events.push({
        id: review.id,
        type: 'review',
        title: `${review.rating}-star review on ${review.platform}`,
        description: `Left a ${review.rating}-star review`,
        timestamp: review.date,
        actor: clientName,
        metadata: { rating: review.rating, platform: review.platform },
        icon: EVENT_ICONS.review,
        color: EVENT_COLORS.review,
      });
    }
  }

  // Sort by timestamp (newest first)
  events.sort((a, b) => b.timestamp.localeCompare(a.timestamp));

  return {
    clientId,
    clientName,
    events,
    totalEvents: events.length,
  };
}

// ─────────────────────────────────────────────────────────────
// NOTE FILTERING & SEARCH
// ─────────────────────────────────────────────────────────────

export interface NoteFilter {
  clientId?: string;
  type?: NoteType;
  createdBy?: string;
  dateFrom?: string;
  dateTo?: string;
  pinnedOnly?: boolean;
  tags?: string[];
  searchQuery?: string;
}

/**
 * Filter notes based on criteria.
 */
export function filterNotes(notes: CRMNote[], filter: NoteFilter): CRMNote[] {
  let filtered = [...notes];

  if (filter.clientId) {
    filtered = filtered.filter(n => n.clientId === filter.clientId);
  }
  if (filter.type) {
    filtered = filtered.filter(n => n.type === filter.type);
  }
  if (filter.createdBy) {
    filtered = filtered.filter(n => n.createdBy === filter.createdBy);
  }
  if (filter.dateFrom) {
    filtered = filtered.filter(n => n.createdAt >= filter.dateFrom!);
  }
  if (filter.dateTo) {
    filtered = filtered.filter(n => n.createdAt <= filter.dateTo!);
  }
  if (filter.pinnedOnly) {
    filtered = filtered.filter(n => n.isPinned);
  }
  if (filter.tags && filter.tags.length > 0) {
    filtered = filtered.filter(n =>
      filter.tags!.some(tag => n.tags.includes(tag)),
    );
  }
  if (filter.searchQuery) {
    const query = filter.searchQuery.toLowerCase();
    filtered = filtered.filter(n =>
      n.subject.toLowerCase().includes(query) ||
      n.content.toLowerCase().includes(query) ||
      n.clientName.toLowerCase().includes(query),
    );
  }

  // Sort: pinned first, then by date
  return filtered.sort((a, b) => {
    if (a.isPinned && !b.isPinned) return -1;
    if (!a.isPinned && b.isPinned) return 1;
    return b.createdAt.localeCompare(a.createdAt);
  });
}

/**
 * Get activity summary stats for a client.
 */
export function getActivitySummary(notes: CRMNote[], clientId: string): {
  totalNotes: number;
  byType: Record<NoteType, number>;
  lastActivity: string | null;
  pinnedCount: number;
} {
  const clientNotes = notes.filter(n => n.clientId === clientId);

  const byType: Record<NoteType, number> = {
    call: 0, email: 0, text: 0, in_person: 0, internal: 0,
  };
  for (const note of clientNotes) {
    byType[note.type]++;
  }

  return {
    totalNotes: clientNotes.length,
    byType,
    lastActivity: clientNotes.length > 0 ? clientNotes[0].createdAt : null,
    pinnedCount: clientNotes.filter(n => n.isPinned).length,
  };
}
