import { NextResponse } from 'next/server';
import { analyzeInventory, type InventoryInput } from '@/lib/inventory/auto-manager';

export async function GET() {
  try {
    // In production, pulls from Airtable inventory items + appointment consumption
    const sampleInput: InventoryInput = {
      items: [
        {
          id: 'botox-50u',
          name: 'Botox (50-unit vial)',
          category: 'injectables',
          currentStock: 8,
          unit: 'vials',
          unitCost: 125,
          expirationDate: '2026-06-15',
          minStock: 5,
          maxStock: 20,
          supplier: 'Allergan',
          leadTimeDays: 5,
        },
        {
          id: 'juvederm-ultra',
          name: 'Juvederm Ultra Plus (1ml)',
          category: 'injectables',
          currentStock: 3,
          unit: 'syringes',
          unitCost: 260,
          expirationDate: '2026-12-01',
          minStock: 5,
          maxStock: 15,
          supplier: 'Allergan',
          leadTimeDays: 5,
        },
        {
          id: 'hydrafacial-serum',
          name: 'HydraFacial Serum Refill',
          category: 'facial_supplies',
          currentStock: 12,
          unit: 'units',
          unitCost: 45,
          expirationDate: '2026-09-01',
          minStock: 6,
          maxStock: 24,
          supplier: 'Edge Systems',
          leadTimeDays: 7,
        },
        {
          id: 'vi-peel-kit',
          name: 'VI Peel Treatment Kit',
          category: 'topicals',
          currentStock: 6,
          unit: 'kits',
          unitCost: 85,
          minStock: 4,
          maxStock: 16,
          supplier: 'VI Aesthetics',
          leadTimeDays: 4,
        },
        {
          id: 'rf-tip-sterile',
          name: 'Secret Pro RF Tips (Sterile)',
          category: 'laser_consumables',
          currentStock: 2,
          unit: 'tips',
          unitCost: 150,
          minStock: 5,
          maxStock: 20,
          supplier: 'Cutera',
          leadTimeDays: 7,
        },
        {
          id: 'numbing-cream',
          name: 'BLT Numbing Cream (30g)',
          category: 'topicals',
          currentStock: 15,
          unit: 'tubes',
          unitCost: 18,
          expirationDate: '2027-01-15',
          minStock: 10,
          maxStock: 30,
          supplier: 'Pharmacy Compounding',
          leadTimeDays: 3,
        },
        {
          id: 'glp1-semaglutide',
          name: 'Semaglutide (2.4mg/0.75ml)',
          category: 'wellness_supplies',
          currentStock: 10,
          unit: 'vials',
          unitCost: 180,
          expirationDate: '2026-08-01',
          minStock: 8,
          maxStock: 25,
          supplier: 'Empower Pharmacy',
          leadTimeDays: 5,
        },
        {
          id: 'nad-vial',
          name: 'NAD+ Injection Vial (500mg)',
          category: 'wellness_supplies',
          currentStock: 6,
          unit: 'vials',
          unitCost: 45,
          expirationDate: '2026-07-01',
          minStock: 4,
          maxStock: 12,
          supplier: 'Empower Pharmacy',
          leadTimeDays: 5,
        },
        {
          id: 'b12-vial',
          name: 'Methylcobalamin B12 (30ml)',
          category: 'wellness_supplies',
          currentStock: 8,
          unit: 'vials',
          unitCost: 12,
          minStock: 5,
          maxStock: 15,
          supplier: 'Empower Pharmacy',
          leadTimeDays: 5,
        },
        {
          id: 'disposable-gloves',
          name: 'Nitrile Gloves (Box of 100)',
          category: 'disposables',
          currentStock: 25,
          unit: 'boxes',
          unitCost: 8,
          minStock: 10,
          maxStock: 50,
          supplier: 'Henry Schein',
          leadTimeDays: 3,
        },
      ],
      appointments: [],
      suppliers: [
        {
          name: 'Allergan',
          items: ['botox-50u', 'juvederm-ultra'],
          avgLeadDays: 5,
          minOrderAmount: 1000,
          bulkDiscountThreshold: 5000,
          bulkDiscountPercent: 8,
          reliability: 95,
        },
        {
          name: 'Empower Pharmacy',
          items: ['glp1-semaglutide', 'nad-vial', 'b12-vial'],
          avgLeadDays: 5,
          minOrderAmount: 500,
          bulkDiscountThreshold: 3000,
          bulkDiscountPercent: 10,
          reliability: 90,
        },
        {
          name: 'Cutera',
          items: ['rf-tip-sterile'],
          avgLeadDays: 7,
          minOrderAmount: 750,
          reliability: 92,
        },
        {
          name: 'Edge Systems',
          items: ['hydrafacial-serum'],
          avgLeadDays: 7,
          minOrderAmount: 300,
          reliability: 88,
        },
        {
          name: 'Henry Schein',
          items: ['disposable-gloves'],
          avgLeadDays: 3,
          minOrderAmount: 100,
          bulkDiscountThreshold: 500,
          bulkDiscountPercent: 5,
          reliability: 97,
        },
      ],
      orderHistory: [],
    };

    const result = analyzeInventory(sampleInput);

    return NextResponse.json({
      success: true,
      data: result,
      generatedAt: new Date().toISOString(),
    });
  } catch (error) {
    console.error('Inventory analysis error:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to analyze inventory' },
      { status: 500 }
    );
  }
}
