import { NextRequest, NextResponse } from 'next/server';
import { getSession } from '@/lib/auth/session';
import { hasPermission } from '@/lib/auth/roles';

/**
 * GET /api/ops/sop
 *
 * The /sop command: returns step-by-step SOPs for medical operations.
 * Accepts query param: process (e.g., new-glp1, refill, emergency)
 */

interface SOPStep {
  step: number;
  title: string;
  description: string;
  owner: 'rina' | 'provider' | 'system' | 'patient';
  estimatedMinutes: number;
  tools?: string[];
  notes?: string;
  critical?: boolean;
}

interface SOP {
  id: string;
  name: string;
  description: string;
  totalSteps: number;
  estimatedTotalMinutes: number;
  frequency: string;
  steps: SOPStep[];
  warnings?: string[];
  lastUpdated: string;
}

// Complete SOP library
const SOPS: Record<string, SOP> = {
  'new-glp1': {
    id: 'new-glp1',
    name: 'New GLP-1 Patient Onboarding',
    description: 'End-to-end process for onboarding a new GLP-1 weight management patient, from intake to first injection.',
    totalSteps: 12,
    estimatedTotalMinutes: 90,
    frequency: 'Per new patient',
    steps: [
      { step: 1, title: 'Receive Intake Form', description: 'Patient submits intake via Typeform. System auto-creates CRM record in Airtable.', owner: 'system', estimatedMinutes: 0, tools: ['Typeform', 'Airtable', 'n8n'] },
      { step: 2, title: 'Run /intake Command', description: 'Process intake through the ops system. Reviews contraindications, determines labs, generates Qualiphy block.', owner: 'rina', estimatedMinutes: 5, tools: ['Ops Dashboard', '/intake'] },
      { step: 3, title: 'Review Contraindication Flags', description: 'Check for hard contraindications (MTC, MEN2, active pancreatitis, pregnancy). If flagged, route to provider review.', owner: 'rina', estimatedMinutes: 3, critical: true, notes: 'Hard contraindications = STOP. Soft contraindications = provider decision.' },
      { step: 4, title: 'Send Welcome Message', description: 'Send welcome text + email generated by /intake. Confirm contact info is correct.', owner: 'rina', estimatedMinutes: 2, tools: ['SMS', 'Email'] },
      { step: 5, title: 'Order Labs', description: 'Send lab order to patient. Include lab list from /intake output. Patient goes to Quest/LabCorp.', owner: 'rina', estimatedMinutes: 5, tools: ['Lab Order Form'], notes: 'Standard: CBC, CMP, Lipid Panel, HbA1c, TSH. Tirzepatide adds: Amylase, Lipase.' },
      { step: 6, title: 'Apply Mangomint Tags', description: 'Apply all tags from /intake output: GLP-1 Patient, New Intake, Labs Needed, medication type.', owner: 'rina', estimatedMinutes: 2, tools: ['Mangomint'] },
      { step: 7, title: 'Monitor Lab Completion', description: 'Track via pipeline. Day 1: auto-reminder. Day 3: nudge. Day 5: escalation call.', owner: 'system', estimatedMinutes: 0, tools: ['/followup', '/pipeline'], notes: 'Use /followup LABS_NEEDED with dayInStage for appropriate message.' },
      { step: 8, title: 'Review Lab Results', description: 'Provider reviews labs. Confirm patient is safe to proceed. Document any concerns.', owner: 'provider', estimatedMinutes: 10, critical: true },
      { step: 9, title: 'Submit Qualiphy GFE', description: 'Enter patient data into Qualiphy for Good Faith Exam. Use quick-entry block from /intake.', owner: 'rina', estimatedMinutes: 10, tools: ['Qualiphy'] },
      { step: 10, title: 'Process Rx Approval', description: 'Once GFE approved, send approval celebration message. Initiate medication order.', owner: 'rina', estimatedMinutes: 5, tools: ['/followup RX_APPROVED'] },
      { step: 11, title: 'Ship Medication', description: 'Process medication shipment. Send tracking info to patient. Update pipeline stage.', owner: 'rina', estimatedMinutes: 5, tools: ['Pharmacy Portal'] },
      { step: 12, title: 'First Dose Instructions', description: 'Send injection instructions when medication arrives. Include side effects guide and emergency contacts.', owner: 'rina', estimatedMinutes: 3, tools: ['/followup ACTIVE_FIRST_DOSE'], notes: 'Always say "injection" - never "infusion."' },
    ],
    warnings: [
      'NEVER proceed past Step 8 without provider lab review and sign-off',
      'Always say "injection" not "infusion"',
      'Document all contraindication decisions in patient record',
    ],
    lastUpdated: '2026-03-20',
  },

  'new-peptide': {
    id: 'new-peptide',
    name: 'New Peptide Therapy Patient',
    description: 'Onboarding process for peptide therapy patients (BPC-157, TB-500, etc).',
    totalSteps: 9,
    estimatedTotalMinutes: 60,
    frequency: 'Per new patient',
    steps: [
      { step: 1, title: 'Receive Intake + Consultation Request', description: 'Patient submits interest form. Schedule consultation.', owner: 'rina', estimatedMinutes: 5, tools: ['Mangomint', 'Airtable'] },
      { step: 2, title: 'Pre-Consult Preparation', description: 'Review patient history. Identify peptide candidates based on goals.', owner: 'rina', estimatedMinutes: 10, tools: ['Consult Co-pilot'] },
      { step: 3, title: 'Provider Consultation', description: 'Provider discusses goals, reviews history, recommends peptide protocol.', owner: 'provider', estimatedMinutes: 30, critical: true },
      { step: 4, title: 'Order Labs if Required', description: 'Some peptides require baseline labs. Order based on protocol.', owner: 'provider', estimatedMinutes: 5 },
      { step: 5, title: 'Process Prescription', description: 'Provider writes prescription. Submit to compounding pharmacy.', owner: 'provider', estimatedMinutes: 5, tools: ['Pharmacy Portal'] },
      { step: 6, title: 'Payment Processing', description: 'Collect payment via Square. Apply any membership discounts.', owner: 'rina', estimatedMinutes: 5, tools: ['Square'] },
      { step: 7, title: 'Medication Arrival + Instructions', description: 'When medication arrives, send injection instructions and storage guidelines.', owner: 'rina', estimatedMinutes: 5, notes: 'Always say "injection" not "infusion."' },
      { step: 8, title: 'Week 1 Check-in', description: 'Check in on tolerance, injection technique, any questions.', owner: 'rina', estimatedMinutes: 3 },
      { step: 9, title: 'Monthly Follow-up', description: 'Schedule monthly provider check-in. Adjust protocol as needed.', owner: 'rina', estimatedMinutes: 3, tools: ['Mangomint'] },
    ],
    lastUpdated: '2026-03-20',
  },

  'new-hormone': {
    id: 'new-hormone',
    name: 'New Hormone Therapy Patient',
    description: 'Onboarding for hormone replacement therapy (HRT) patients.',
    totalSteps: 10,
    estimatedTotalMinutes: 75,
    frequency: 'Per new patient',
    steps: [
      { step: 1, title: 'Receive Intake + Symptom Assessment', description: 'Patient completes intake with hormone symptom checklist.', owner: 'system', estimatedMinutes: 0, tools: ['Typeform'] },
      { step: 2, title: 'Order Comprehensive Hormone Panel', description: 'Full hormone panel: Total/Free Testosterone, Estradiol, Progesterone, DHEA-S, Cortisol, Thyroid panel, IGF-1.', owner: 'rina', estimatedMinutes: 5, critical: true },
      { step: 3, title: 'Schedule Provider Consultation', description: 'Book 45-min consultation after labs received.', owner: 'rina', estimatedMinutes: 3, tools: ['Mangomint'] },
      { step: 4, title: 'Provider Lab Review + Plan', description: 'Provider reviews hormone levels, creates treatment plan.', owner: 'provider', estimatedMinutes: 30, critical: true },
      { step: 5, title: 'Patient Education Session', description: 'Explain protocol, injection technique, monitoring schedule.', owner: 'provider', estimatedMinutes: 15 },
      { step: 6, title: 'Process Prescription', description: 'Write and submit prescription to compounding pharmacy.', owner: 'provider', estimatedMinutes: 5, tools: ['Pharmacy Portal'] },
      { step: 7, title: 'Payment + Membership Setup', description: 'Process payment. Recommend monthly membership for ongoing care.', owner: 'rina', estimatedMinutes: 5, tools: ['Square', 'Mangomint'] },
      { step: 8, title: 'First Injection Appointment', description: 'In-office first injection with provider supervision.', owner: 'provider', estimatedMinutes: 20, notes: 'First injection always in-office for safety monitoring.' },
      { step: 9, title: '6-Week Follow-up Labs', description: 'Order follow-up hormone panel to check levels. Adjust if needed.', owner: 'rina', estimatedMinutes: 5, critical: true },
      { step: 10, title: 'Quarterly Lab Monitoring', description: 'Set up recurring quarterly lab schedule. Auto-reminders.', owner: 'system', estimatedMinutes: 0, tools: ['n8n', 'Mangomint'] },
    ],
    warnings: [
      'Hormone therapy requires regular lab monitoring - never skip quarterly labs',
      'First injection must be supervised in-office',
      'Document all dosage changes in patient record',
    ],
    lastUpdated: '2026-03-20',
  },

  'titration': {
    id: 'titration',
    name: 'GLP-1 Dose Titration',
    description: 'Process for adjusting GLP-1 medication dosage based on patient response.',
    totalSteps: 7,
    estimatedTotalMinutes: 30,
    frequency: 'Monthly or as needed',
    steps: [
      { step: 1, title: 'Review Patient Progress', description: 'Check weight loss, side effects, and tolerance from past 4 weeks.', owner: 'rina', estimatedMinutes: 5 },
      { step: 2, title: 'Assess Side Effects', description: 'Document any nausea, constipation, or injection site reactions. Rate severity 1-5.', owner: 'rina', estimatedMinutes: 3 },
      { step: 3, title: 'Provider Titration Decision', description: 'Provider reviews data and decides: maintain, increase, or hold dose.', owner: 'provider', estimatedMinutes: 5, critical: true },
      { step: 4, title: 'Update Dose in System', description: 'Update patient record with new dose, effective date, and rationale.', owner: 'rina', estimatedMinutes: 2, tools: ['Airtable'] },
      { step: 5, title: 'Notify Patient', description: 'Send dose change notification with updated injection instructions.', owner: 'rina', estimatedMinutes: 3, tools: ['/followup'] },
      { step: 6, title: 'Adjust Refill Order', description: 'If dose changed, update next refill to reflect new dosage.', owner: 'rina', estimatedMinutes: 5, tools: ['Pharmacy Portal'] },
      { step: 7, title: 'Schedule Next Review', description: 'Book next titration review in 4 weeks.', owner: 'system', estimatedMinutes: 0 },
    ],
    lastUpdated: '2026-03-20',
  },

  'refill': {
    id: 'refill',
    name: 'Medication Refill Processing',
    description: 'Standard process for processing monthly medication refills.',
    totalSteps: 6,
    estimatedTotalMinutes: 15,
    frequency: 'Monthly per patient',
    steps: [
      { step: 1, title: 'Run /refills Command', description: 'Check who is due for refill in the next 7-14 days.', owner: 'rina', estimatedMinutes: 2, tools: ['/refills'] },
      { step: 2, title: 'Verify Patient Status', description: 'Confirm patient is active, no safety concerns, payment is current.', owner: 'rina', estimatedMinutes: 2 },
      { step: 3, title: 'Process Payment', description: 'Charge recurring payment via Square. Handle failures immediately.', owner: 'rina', estimatedMinutes: 2, tools: ['Square'] },
      { step: 4, title: 'Submit Refill Order', description: 'Place order with pharmacy. Confirm dosage matches current protocol.', owner: 'rina', estimatedMinutes: 3, tools: ['Pharmacy Portal'] },
      { step: 5, title: 'Send Confirmation', description: 'Notify patient that refill is processing. Include shipping estimate.', owner: 'rina', estimatedMinutes: 2, tools: ['/followup REFILL_DUE'] },
      { step: 6, title: 'Track Delivery', description: 'Monitor shipment. Send tracking when available.', owner: 'system', estimatedMinutes: 0 },
    ],
    lastUpdated: '2026-03-20',
  },

  'quarterly-labs': {
    id: 'quarterly-labs',
    name: 'Quarterly Lab Monitoring',
    description: 'Routine quarterly lab work for active GLP-1 and hormone therapy patients.',
    totalSteps: 5,
    estimatedTotalMinutes: 20,
    frequency: 'Quarterly per patient',
    steps: [
      { step: 1, title: 'Identify Patients Due', description: 'Pull list of patients due for quarterly labs (90 days since last).', owner: 'rina', estimatedMinutes: 3, tools: ['Airtable'] },
      { step: 2, title: 'Send Lab Reminder', description: 'Notify patients that quarterly labs are due. Include lab list.', owner: 'rina', estimatedMinutes: 5, tools: ['/followup'] },
      { step: 3, title: 'Track Lab Completion', description: 'Monitor who has completed labs. Follow up at 3, 5, 7 days.', owner: 'system', estimatedMinutes: 0, tools: ['/pipeline'] },
      { step: 4, title: 'Provider Lab Review', description: 'Provider reviews results, flags any concerns, documents findings.', owner: 'provider', estimatedMinutes: 10, critical: true },
      { step: 5, title: 'Patient Communication', description: 'Share results with patient. If adjustments needed, schedule appointment.', owner: 'rina', estimatedMinutes: 5 },
    ],
    warnings: ['Do not skip quarterly labs for any active patient', 'Flag abnormal results to provider immediately'],
    lastUpdated: '2026-03-20',
  },

  'emergency': {
    id: 'emergency',
    name: 'Medical Emergency Protocol',
    description: 'Steps for handling adverse reactions or medical emergencies related to treatments.',
    totalSteps: 8,
    estimatedTotalMinutes: 30,
    frequency: 'As needed (rare)',
    steps: [
      { step: 1, title: 'Assess Severity', description: 'Determine if this is a true emergency (anaphylaxis, severe reaction) or manageable side effect.', owner: 'rina', estimatedMinutes: 1, critical: true, notes: 'If patient reports difficulty breathing, swelling of face/throat, or chest pain: CALL 911 FIRST.' },
      { step: 2, title: 'Emergency: Call 911', description: 'For severe reactions: Call 911. Stay on line with patient. Do not hang up.', owner: 'rina', estimatedMinutes: 2, critical: true },
      { step: 3, title: 'Notify Provider Immediately', description: 'Call provider directly. Do not text or email for emergencies.', owner: 'rina', estimatedMinutes: 1, critical: true },
      { step: 4, title: 'Guide Patient to ER if Needed', description: 'If not 911-level but needs medical attention, guide to nearest ER.', owner: 'rina', estimatedMinutes: 5 },
      { step: 5, title: 'Document Everything', description: 'Record: time of onset, symptoms, medication/dose, last injection date, actions taken.', owner: 'rina', estimatedMinutes: 5, tools: ['Airtable'] },
      { step: 6, title: 'Pause Medication', description: 'Immediately pause medication. Do NOT instruct patient to take next dose until provider clears.', owner: 'provider', estimatedMinutes: 1, critical: true },
      { step: 7, title: 'Follow-up Within 24 Hours', description: 'Check on patient within 24 hours. Document outcome.', owner: 'rina', estimatedMinutes: 5 },
      { step: 8, title: 'Provider Review + Protocol Adjustment', description: 'Provider reviews case. Decide: resume at lower dose, switch medication, or discontinue.', owner: 'provider', estimatedMinutes: 15, critical: true },
    ],
    warnings: [
      'ALWAYS err on the side of caution - call 911 if uncertain',
      'Never tell a patient to "wait and see" with breathing difficulty or severe swelling',
      'Document EVERYTHING with timestamps',
      'This SOP does not replace clinical judgment',
    ],
    lastUpdated: '2026-03-20',
  },

  'churn-save': {
    id: 'churn-save',
    name: 'Churn Prevention / Save',
    description: 'Process for retaining patients who show signs of churning or explicitly want to cancel.',
    totalSteps: 7,
    estimatedTotalMinutes: 30,
    frequency: 'As needed',
    steps: [
      { step: 1, title: 'Identify Churn Signal', description: 'Triggered by: missed refill, no response 5+ days, payment failure, or explicit cancellation request.', owner: 'system', estimatedMinutes: 0, tools: ['/pipeline', '/refills'] },
      { step: 2, title: 'Personal Outreach from Rina', description: 'Call (not text) the patient. Ask how they are doing. Listen for the real reason.', owner: 'rina', estimatedMinutes: 10, critical: true, notes: 'Common reasons: cost, side effects, no results, forgot, life changes.' },
      { step: 3, title: 'Address Root Cause', description: 'Cost: offer payment plan or tier adjustment. Side effects: route to provider. No results: review compliance + titration.', owner: 'rina', estimatedMinutes: 5 },
      { step: 4, title: 'Offer Save Options', description: 'Options: 1) Pause 1 month (not cancel), 2) Downgrade tier, 3) Add wellness injection for better results, 4) Schedule provider call.', owner: 'rina', estimatedMinutes: 5 },
      { step: 5, title: 'Document Decision', description: 'Record outcome: saved, paused, downgraded, or lost. Include reason.', owner: 'rina', estimatedMinutes: 2, tools: ['Airtable'] },
      { step: 6, title: 'If Saved: Schedule Next Touch', description: 'Set follow-up within 7 days. Extra attention for next 30 days.', owner: 'rina', estimatedMinutes: 2 },
      { step: 7, title: 'If Lost: Move to Win-Back', description: 'Move to WIN_BACK stage. Run /winback for re-engagement sequence.', owner: 'rina', estimatedMinutes: 3, tools: ['/winback'] },
    ],
    warnings: ['Never make the patient feel guilty for considering cancellation', 'A pause is always better than a cancellation'],
    lastUpdated: '2026-03-20',
  },

  'payment-failed': {
    id: 'payment-failed',
    name: 'Failed Payment Recovery',
    description: 'Process for handling failed recurring payments.',
    totalSteps: 6,
    estimatedTotalMinutes: 15,
    frequency: 'As needed',
    steps: [
      { step: 1, title: 'Detect Payment Failure', description: 'System detects failed charge via Square. Alert generated.', owner: 'system', estimatedMinutes: 0, tools: ['Square', 'n8n'] },
      { step: 2, title: 'Send Friendly Notification', description: 'Text patient about payment issue. Keep it casual - "Hey, looks like your card didn\'t go through."', owner: 'rina', estimatedMinutes: 2, notes: 'Never say "payment failed" - say "there was a hiccup with your card."' },
      { step: 3, title: 'Retry Payment (Day 2)', description: 'Auto-retry charge. If success, send confirmation and move on.', owner: 'system', estimatedMinutes: 0, tools: ['Square'] },
      { step: 4, title: 'Second Outreach (Day 3)', description: 'If still failed, call patient. Offer to update card info. Be helpful, not pushy.', owner: 'rina', estimatedMinutes: 5 },
      { step: 5, title: 'Final Notice (Day 5)', description: 'Last attempt. Explain medication will be paused if not resolved. Offer alternatives.', owner: 'rina', estimatedMinutes: 3 },
      { step: 6, title: 'Resolve or Pause', description: 'If resolved: process refill. If not: pause medication, move to AT_RISK, run churn-save.', owner: 'rina', estimatedMinutes: 5, tools: ['/pipeline'] },
    ],
    warnings: ['Never shame a patient about payment', 'Always offer solutions, not ultimatums'],
    lastUpdated: '2026-03-20',
  },
};

const VALID_PROCESSES = Object.keys(SOPS);

export async function GET(request: NextRequest) {
  try {
    const session = await getSession();
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    if (!hasPermission(session.role, 'view_clients')) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    const { searchParams } = new URL(request.url);
    const process = searchParams.get('process');

    // No process specified: return list of all SOPs
    if (!process) {
      const sopList = Object.values(SOPS).map((sop) => ({
        id: sop.id,
        name: sop.name,
        description: sop.description,
        totalSteps: sop.totalSteps,
        estimatedTotalMinutes: sop.estimatedTotalMinutes,
        frequency: sop.frequency,
        lastUpdated: sop.lastUpdated,
      }));

      return NextResponse.json({
        success: true,
        data: {
          availableProcesses: VALID_PROCESSES,
          sops: sopList,
          usage: 'GET /api/ops/sop?process=new-glp1',
        },
      });
    }

    // Specific SOP requested
    const sop = SOPS[process];
    if (!sop) {
      return NextResponse.json(
        {
          error: `Unknown process: ${process}`,
          availableProcesses: VALID_PROCESSES,
          hint: 'Use one of the available process names as the query parameter.',
        },
        { status: 404 }
      );
    }

    return NextResponse.json({
      success: true,
      data: sop,
    });
  } catch (error) {
    console.error('[/api/ops/sop] Error:', error);
    return NextResponse.json(
      { error: 'Failed to load SOP', details: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    );
  }
}
