/**
 * Notes & Activity Logging Tests — 35 tests
 */

import {
  createNote,
  createAutoNote,
  togglePin,
  updateNote,
  addMention,
  getTemplate,
  renderTemplate,
  buildClientTimeline,
  filterNotes,
  getActivitySummary,
  NOTE_TEMPLATES,
} from '../notes';
import type { CRMNote, NoteFilter, NoteTemplate } from '@/types/crm';

function makeNote(overrides: Partial<CRMNote> = {}): CRMNote {
  return {
    id: 'note_test',
    clientId: 'c_test',
    clientName: 'Test Client',
    type: 'call',
    subject: 'Test note',
    content: 'Test content',
    createdBy: 'Rina',
    createdAt: '2026-03-25T14:00:00Z',
    updatedAt: '2026-03-25T14:00:00Z',
    isPinned: false,
    mentions: [],
    tags: [],
    attachments: [],
    isAutoGenerated: false,
    ...overrides,
  };
}

// ─── Note Creation Tests ─────────────────────────────────────

describe('Notes - Creation', () => {
  test('should create note with required fields', () => {
    const note = createNote({
      clientId: 'c001',
      clientName: 'Sarah',
      type: 'call',
      subject: 'Follow-up call',
      content: 'Discussed treatment options',
      createdBy: 'Rina',
    });
    expect(note.id).toMatch(/^note_/);
    expect(note.clientId).toBe('c001');
    expect(note.type).toBe('call');
    expect(note.isAutoGenerated).toBe(false);
  });

  test('should create note with tags and mentions', () => {
    const note = createNote({
      clientId: 'c001',
      clientName: 'Sarah',
      type: 'internal',
      subject: 'Team note',
      content: 'Review this client',
      createdBy: 'Rina',
      tags: ['priority', 'vip'],
      mentions: ['Mom'],
    });
    expect(note.tags).toEqual(['priority', 'vip']);
    expect(note.mentions).toEqual(['Mom']);
  });

  test('should create pinned note', () => {
    const note = createNote({
      clientId: 'c001',
      clientName: 'Sarah',
      type: 'internal',
      subject: 'Important',
      content: 'VIP client preferences',
      createdBy: 'Rina',
      isPinned: true,
    });
    expect(note.isPinned).toBe(true);
  });

  test('should create auto-generated note', () => {
    const note = createAutoNote('c001', 'Sarah', 'Stage Changed', 'Moved to Consulted', 'auto_002');
    expect(note.isAutoGenerated).toBe(true);
    expect(note.createdBy).toBe('system');
    expect(note.automationId).toBe('auto_002');
    expect(note.tags).toContain('auto_generated');
  });

  test('should set timestamps on creation', () => {
    const note = createNote({
      clientId: 'c001', clientName: 'Sarah', type: 'call',
      subject: 'Test', content: 'Test', createdBy: 'Rina',
    });
    expect(note.createdAt).toBeDefined();
    expect(note.updatedAt).toBeDefined();
  });
});

// ─── Note Management Tests ───────────────────────────────────

describe('Notes - Management', () => {
  test('should toggle pin', () => {
    const note = makeNote({ isPinned: false });
    const pinned = togglePin(note);
    expect(pinned.isPinned).toBe(true);
    const unpinned = togglePin(pinned);
    expect(unpinned.isPinned).toBe(false);
  });

  test('should update note content', () => {
    const note = makeNote();
    const updated = updateNote(note, { subject: 'Updated subject', content: 'Updated content' });
    expect(updated.subject).toBe('Updated subject');
    expect(updated.content).toBe('Updated content');
    expect(updated.updatedAt).not.toBe(note.updatedAt);
  });

  test('should update note tags', () => {
    const note = makeNote({ tags: ['old'] });
    const updated = updateNote(note, { tags: ['new', 'tag'] });
    expect(updated.tags).toEqual(['new', 'tag']);
  });

  test('should add mention', () => {
    const note = makeNote({ mentions: [] });
    const withMention = addMention(note, 'Mom');
    expect(withMention.mentions).toContain('Mom');
  });

  test('should not duplicate mentions', () => {
    const note = makeNote({ mentions: ['Rina'] });
    const result = addMention(note, 'Rina');
    expect(result.mentions).toHaveLength(1);
  });
});

// ─── Template Tests ──────────────────────────────────────────

describe('Notes - Templates', () => {
  test('should have at least 5 templates', () => {
    expect(NOTE_TEMPLATES.length).toBeGreaterThanOrEqual(5);
  });

  test('should have unique template IDs', () => {
    const ids = NOTE_TEMPLATES.map(t => t.id);
    expect(new Set(ids).size).toBe(NOTE_TEMPLATES.length);
  });

  test('should get template by ID', () => {
    const template = getTemplate('tpl_call_followup');
    expect(template).toBeDefined();
    expect(template!.type).toBe('call');
  });

  test('should return undefined for unknown template', () => {
    expect(getTemplate('nonexistent')).toBeUndefined();
  });

  test('should render template with variables', () => {
    const template = getTemplate('tpl_call_followup')!;
    const rendered = renderTemplate(template, {
      clientName: 'Sarah Johnson',
      reason: 'treatment plan follow-up',
      outcome: 'Interested, needs more time',
      nextSteps: 'Call again Friday',
      followUpDate: '2026-03-28',
    });
    expect(rendered.subject).toContain('Sarah Johnson');
    expect(rendered.content).toContain('treatment plan follow-up');
    expect(rendered.content).toContain('Call again Friday');
  });

  test('should handle missing variables gracefully', () => {
    const template = getTemplate('tpl_call_followup')!;
    const rendered = renderTemplate(template, { clientName: 'Sarah' });
    expect(rendered.subject).toContain('Sarah');
    expect(rendered.content).toContain('{{reason}}'); // Unreplaced
  });

  test('should have variables list for each template', () => {
    for (const template of NOTE_TEMPLATES) {
      expect(template.variables.length).toBeGreaterThan(0);
    }
  });

  test('should include consultation notes template', () => {
    const template = getTemplate('tpl_consult_notes');
    expect(template).toBeDefined();
    expect(template!.type).toBe('in_person');
  });
});

// ─── Timeline Tests ──────────────────────────────────────────

describe('Notes - Client Timeline', () => {
  test('should build timeline from notes', () => {
    const timeline = buildClientTimeline('c001', 'Sarah', {
      notes: [makeNote()],
    });
    expect(timeline.events).toHaveLength(1);
    expect(timeline.events[0].type).toBe('note');
  });

  test('should build timeline from appointments', () => {
    const timeline = buildClientTimeline('c001', 'Sarah', {
      appointments: [
        { id: 'a1', service: 'Botox', date: '2026-03-20', provider: 'Rina', status: 'Completed' },
      ],
    });
    expect(timeline.events).toHaveLength(1);
    expect(timeline.events[0].type).toBe('appointment');
  });

  test('should build timeline from transactions', () => {
    const timeline = buildClientTimeline('c001', 'Sarah', {
      transactions: [
        { id: 't1', date: '2026-03-20', amount: 500, service: 'Botox', type: 'Payment' },
      ],
    });
    expect(timeline.events).toHaveLength(1);
    expect(timeline.events[0].type).toBe('transaction');
  });

  test('should combine all event types', () => {
    const timeline = buildClientTimeline('c001', 'Sarah', {
      notes: [makeNote()],
      appointments: [{ id: 'a1', service: 'Botox', date: '2026-03-20', provider: 'Rina', status: 'Completed' }],
      transactions: [{ id: 't1', date: '2026-03-20', amount: 500, service: 'Botox', type: 'Payment' }],
      stageChanges: [{ from: 'new_lead', to: 'contacted', at: '2026-03-18', by: 'Rina' }],
      milestones: [{ label: '1st Visit', achievedAt: '2026-03-15' }],
      reviews: [{ id: 'r1', rating: 5, date: '2026-03-22', platform: 'Google' }],
    });
    expect(timeline.events.length).toBeGreaterThanOrEqual(5);
    expect(timeline.totalEvents).toBeGreaterThanOrEqual(5);
  });

  test('should sort events newest first', () => {
    const timeline = buildClientTimeline('c001', 'Sarah', {
      notes: [
        makeNote({ id: 'old', createdAt: '2026-03-15T10:00:00Z' }),
        makeNote({ id: 'new', createdAt: '2026-03-25T10:00:00Z' }),
      ],
    });
    expect(timeline.events[0].id).toBe('new');
  });

  test('should include stage changes', () => {
    const timeline = buildClientTimeline('c001', 'Sarah', {
      stageChanges: [
        { from: 'new_lead', to: 'contacted', at: '2026-03-18T10:00:00Z', by: 'Rina' },
      ],
    });
    expect(timeline.events[0].type).toBe('stage_change');
    expect(timeline.events[0].title).toContain('new_lead');
  });

  test('should handle empty data', () => {
    const timeline = buildClientTimeline('c001', 'Sarah', {});
    expect(timeline.events).toHaveLength(0);
    expect(timeline.totalEvents).toBe(0);
  });
});

// ─── Note Filtering Tests ────────────────────────────────────

describe('Notes - Filtering', () => {
  const notes = [
    makeNote({ id: 'n1', clientId: 'c001', type: 'call', isPinned: true, tags: ['vip'] }),
    makeNote({ id: 'n2', clientId: 'c001', type: 'email', createdBy: 'system' }),
    makeNote({ id: 'n3', clientId: 'c002', type: 'call', subject: 'Injection follow-up', content: 'Called about Botox results' }),
  ];

  test('should filter by clientId', () => {
    const result = filterNotes(notes, { clientId: 'c001' });
    expect(result).toHaveLength(2);
  });

  test('should filter by type', () => {
    const result = filterNotes(notes, { type: 'call' });
    expect(result).toHaveLength(2);
  });

  test('should filter by pinned', () => {
    const result = filterNotes(notes, { pinnedOnly: true });
    expect(result).toHaveLength(1);
    expect(result[0].id).toBe('n1');
  });

  test('should filter by tags', () => {
    const result = filterNotes(notes, { tags: ['vip'] });
    expect(result).toHaveLength(1);
  });

  test('should filter by search query', () => {
    const result = filterNotes(notes, { searchQuery: 'Botox' });
    expect(result).toHaveLength(1);
    expect(result[0].id).toBe('n3');
  });

  test('should sort pinned notes first', () => {
    const result = filterNotes(notes, {});
    expect(result[0].isPinned).toBe(true);
  });
});

// ─── Activity Summary Tests ──────────────────────────────────

describe('Notes - Activity Summary', () => {
  test('should summarize activity for a client', () => {
    const notes = [
      makeNote({ clientId: 'c001', type: 'call' }),
      makeNote({ id: 'n2', clientId: 'c001', type: 'email' }),
      makeNote({ id: 'n3', clientId: 'c001', type: 'call', isPinned: true }),
      makeNote({ id: 'n4', clientId: 'c002', type: 'call' }),
    ];
    const summary = getActivitySummary(notes, 'c001');
    expect(summary.totalNotes).toBe(3);
    expect(summary.byType.call).toBe(2);
    expect(summary.byType.email).toBe(1);
    expect(summary.pinnedCount).toBe(1);
  });

  test('should return null lastActivity for no notes', () => {
    const summary = getActivitySummary([], 'c999');
    expect(summary.totalNotes).toBe(0);
    expect(summary.lastActivity).toBeNull();
  });

  test('should track all note types', () => {
    const summary = getActivitySummary([], 'c001');
    expect(summary.byType.call).toBe(0);
    expect(summary.byType.email).toBe(0);
    expect(summary.byType.text).toBe(0);
    expect(summary.byType.in_person).toBe(0);
    expect(summary.byType.internal).toBe(0);
  });
});
